"""
OpenClaw-style Business Recommendation Engine.

Reads geospatial risk model predictions, historic outage data, and
charging site locations to generate actionable business recommendations
for EV charging station placement and grid resilience investment.

Features:
* Template-based natural language generation (no LLM dependency).
* Optional LLM integration when OPENAI_API_KEY or ANTHROPIC_API_KEY
  is set in the environment.
* Cross-references risk predictions with community building locations.
* Generates ranked investment priorities.

Usage as library::

    from advanced_charts.recommendation_engine import RecommendationEngine
    engine = RecommendationEngine(predictions, outages, charging_sites)
    insights = engine.generate_all_insights()
    answer = engine.ask("Where should we put new chargers?")

Usage standalone::

    python recommendation_engine.py              # Generate full report
    python recommendation_engine.py --ask "..."  # Ask a question
"""

from __future__ import annotations

import logging
import os
from dataclasses import dataclass, field
from math import radians, sin, cos, sqrt, atan2
from pathlib import Path

import numpy as np
import pandas as pd

log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

DATA_DIR = Path(__file__).parent.parent / "data"
CHARGING_SITES_FILE = DATA_DIR / "all_charging_sites.csv"
REPORT_CACHE = DATA_DIR / "recommendations_cache.pkl"

# Haversine distance helper

def haversine_km(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    R = 6371.0
    lat1_r, lon1_r = radians(lat1), radians(lon1)
    lat2_r, lon2_r = radians(lat2), radians(lon2)
    dlat = lat2_r - lat1_r
    dlon = lon2_r - lon1_r
    a = sin(dlat / 2) ** 2 + cos(lat1_r) * cos(lat2_r) * sin(dlon / 2) ** 2
    return R * 2 * atan2(sqrt(a), sqrt(1 - a))


def haversine_vec(lat1, lon1, lat2_arr, lon2_arr):
    """Vectorised Haversine."""
    R = 6371.0
    lat1_r = np.radians(lat1)
    lon1_r = np.radians(lon1)
    lat2_r = np.radians(lat2_arr)
    lon2_r = np.radians(lon2_arr)
    dlat = lat2_r - lat1_r
    dlon = lon2_r - lon1_r
    a = np.sin(dlat / 2) ** 2 + np.cos(lat1_r) * np.cos(lat2_r) * np.sin(dlon / 2) ** 2
    return R * 2 * np.arctan2(np.sqrt(a), np.sqrt(1 - a))


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------


@dataclass
class Recommendation:
    """A single business recommendation."""
    category: str           # e.g. "Charging Station Placement", "Grid Resilience"
    priority: str           # "Critical", "High", "Medium", "Low"
    title: str
    detail: str
    location: tuple | None = None  # (lat, lon) if applicable
    score: float = 0.0


@dataclass
class InsightReport:
    """Full report generated by the recommendation engine."""
    recommendations: list[Recommendation] = field(default_factory=list)
    summary: str = ""
    investment_ranking: pd.DataFrame = field(default_factory=pd.DataFrame)


# ---------------------------------------------------------------------------
# Recommendation Engine
# ---------------------------------------------------------------------------


class RecommendationEngine:
    """Generate business recommendations from risk predictions and outage data.

    Parameters
    ----------
    predictions : pd.DataFrame
        Risk model output with columns: lat, lon, risk_level, confidence,
        prob_low, prob_medium, prob_high.
    outages : pd.DataFrame
        Historic unplanned outages (cleaned).
    charging_sites : pd.DataFrame
        Charging site locations with columns: charge_point_location,
        site_category, latitude, longitude.
    """

    def __init__(
        self,
        predictions: pd.DataFrame,
        outages: pd.DataFrame,
        charging_sites: pd.DataFrame | None = None,
    ):
        self.predictions = predictions.copy()
        self.outages = outages.copy()
        self.charging_sites = (
            charging_sites.copy() if charging_sites is not None
            else self._load_default_sites()
        )

        # Community buildings: sites with "Village Hall" or "Community Centre" in name
        self.community_buildings = self.charging_sites[
            self.charging_sites["charge_point_location"].str.contains(
                "Village Hall|Community Centre|Community Center", case=False, na=False
            )
        ].copy()

    @staticmethod
    def _load_default_sites() -> pd.DataFrame:
        if CHARGING_SITES_FILE.exists():
            return pd.read_csv(CHARGING_SITES_FILE)
        return pd.DataFrame(columns=["charge_point_location", "site_category", "latitude", "longitude"])

    def _nearest_community_building(self, lat: float, lon: float) -> dict | None:
        """Return the nearest community building to a given point."""
        if self.community_buildings.empty:
            return None
        dists = haversine_vec(
            lat, lon,
            self.community_buildings["latitude"].values,
            self.community_buildings["longitude"].values,
        )
        idx = dists.argmin()
        return {
            "name": self.community_buildings.iloc[idx]["charge_point_location"],
            "distance": dists[idx],
            "lat": self.community_buildings.iloc[idx]["latitude"],
            "lon": self.community_buildings.iloc[idx]["longitude"],
        }

    # ------------------------------------------------------------------
    # Insight generators
    # ------------------------------------------------------------------

    def _find_nearest_location_name(self, lat: float, lon: float) -> str:
        """Find the nearest named location to given coordinates.

        Searches through charging sites and community buildings to find
        the closest named location.
        """
        best_name = None
        best_dist = float("inf")

        # Search charging sites
        if not self.charging_sites.empty and "latitude" in self.charging_sites.columns:
            dists = haversine_vec(
                lat, lon,
                self.charging_sites["latitude"].values,
                self.charging_sites["longitude"].values,
            )
            min_idx = dists.argmin()
            if dists[min_idx] < best_dist:
                best_dist = dists[min_idx]
                best_name = self.charging_sites.iloc[min_idx]["charge_point_location"]

        # Search community buildings
        if not self.community_buildings.empty:
            dists = haversine_vec(
                lat, lon,
                self.community_buildings["latitude"].values,
                self.community_buildings["longitude"].values,
            )
            min_idx = dists.argmin()
            if dists[min_idx] < best_dist:
                best_dist = dists[min_idx]
                best_name = self.community_buildings.iloc[min_idx]["charge_point_location"]

        # If no nearby named location, try to get town name from outages
        if best_name is None or best_dist > 5.0:
            if not self.outages.empty and "latitude" in self.outages.columns:
                dists = haversine_vec(
                    lat, lon,
                    self.outages["latitude"].values,
                    self.outages["longitude"].values,
                )
                min_idx = dists.argmin()
                if dists[min_idx] < 10.0:
                    # Try to get location info from outages
                    if "district_name" in self.outages.columns:
                        best_name = self.outages.iloc[min_idx]["district_name"]
                    elif "primary_substation" in self.outages.columns:
                        best_name = self.outages.iloc[min_idx]["primary_substation"]

        return best_name if best_name else f"Area near ({lat:.2f}, {lon:.2f})"

    def charging_station_recommendations(self) -> list[Recommendation]:
        """Find high-risk areas without V2X coverage."""
        recs = []
        high_risk = self.predictions[self.predictions["risk_level"] == "High"].copy()
        if high_risk.empty:
            return recs

        v2x_sites = self.charging_sites[
            self.charging_sites["site_category"] == "V2X Chargepoint"
        ]

        for _, cell in high_risk.iterrows():
            lat, lon = cell["lat"], cell["lon"]

            # Check if any V2X site is within 3 km
            if not v2x_sites.empty:
                dists = haversine_vec(
                    lat, lon,
                    v2x_sites["latitude"].values,
                    v2x_sites["longitude"].values,
                )
                nearest_v2x_dist = dists.min()
                nearest_v2x_name = v2x_sites.iloc[dists.argmin()]["charge_point_location"]
            else:
                nearest_v2x_dist = float("inf")
                nearest_v2x_name = "N/A"

            if nearest_v2x_dist > 3.0:
                # Find nearest community building
                comm_info = self._nearest_community_building(lat, lon)

                # Get location name instead of coordinates
                location_name = self._find_nearest_location_name(lat, lon)

                detail = (
                    f"High-risk area near **{location_name}** has no V2X coverage "
                    f"within 3 km. Nearest V2X site: {nearest_v2x_name} "
                    f"({nearest_v2x_dist:.1f} km away). "
                    f"Confidence: {cell['confidence']:.0%}."
                )
                if comm_info:
                    detail += (
                        f" Nearest community building: {comm_info['name']} "
                        f"({comm_info['distance']:.1f} km). "
                        f"V2X deployment here could provide backup power for the community."
                    )

                recs.append(Recommendation(
                    category="Charging Station Placement",
                    priority="Critical",
                    title=f"V2X deployment recommended at {location_name}",
                    detail=detail,
                    location=(lat, lon),
                    score=cell["confidence"],
                ))

        # Sort by confidence, return top 3
        recs.sort(key=lambda r: r.score, reverse=True)
        return recs[:3]

    def grid_resilience_recommendations(self) -> list[Recommendation]:
        """Identify districts with high outage burden."""
        recs = []
        if self.outages.empty or "district_name" not in self.outages.columns:
            return recs

        df = self.outages.copy()
        df["duration-hours"] = pd.to_numeric(df["duration-hours"], errors="coerce").fillna(0)

        # District-level stats
        stats = df.groupby("district_name").agg(
            outage_count=("duration-hours", "size"),
            avg_duration=("duration-hours", "mean"),
            total_hours=("duration-hours", "sum"),
        ).reset_index()

        # Winter outages
        if "season" in df.columns:
            winter = df[df["season"] == "Winter"].groupby("district_name").size()
            stats = stats.merge(winter.rename("winter_count"), on="district_name", how="left")
            stats["winter_count"] = stats["winter_count"].fillna(0)
        else:
            stats["winter_count"] = 0

        for _, row in stats.nlargest(5, "outage_count").iterrows():
            priority = "High" if row["outage_count"] > 50 else "Medium"
            detail = (
                f"{row['district_name']} experienced {row['outage_count']} outages "
                f"(avg {row['avg_duration']:.1f}h each, {row['total_hours']:.0f}h total). "
                f"{row['winter_count']:.0f} occurred in winter. "
            )
            if row["winter_count"] > 20:
                detail += "High winter vulnerability — priority for infrastructure upgrade."

            recs.append(Recommendation(
                category="Grid Resilience",
                priority=priority,
                title=f"Grid resilience priority: {row['district_name']}",
                detail=detail,
                score=row["outage_count"],
            ))

        return recs

    def community_impact_recommendations(self) -> list[Recommendation]:
        """Assess impact on community buildings."""
        recs = []
        if self.community_buildings.empty:
            return recs

        for _, building in self.community_buildings.iterrows():
            b_lat, b_name = building["latitude"], building["charge_point_location"]

            # Count outages within 2 km
            if not self.outages.empty and "latitude" in self.outages.columns:
                dists = haversine_vec(
                    b_lat, building["longitude"],
                    self.outages["latitude"].values,
                    self.outages["longitude"].values,
                )
                nearby = self.outages[dists <= 2.0]
                count = len(nearby)
                total_hours = pd.to_numeric(nearby["duration-hours"], errors="coerce").sum()
            else:
                count, total_hours = 0, 0

            # Check if building has V2X
            site_cat = building.get("site_category", "")
            has_v2x = site_cat == "V2X Chargepoint"

            if count > 5:
                priority = "High" if not has_v2x else "Medium"
                detail = (
                    f"{b_name} has experienced {count} nearby outages "
                    f"({total_hours:.0f} hours total impact). "
                )
                if has_v2x:
                    detail += "Site already has V2X — can provide backup power during outages."
                else:
                    detail += "No V2X backup available — community is vulnerable during outages."

                recs.append(Recommendation(
                    category="Community Impact",
                    priority=priority,
                    title=f"Community building at risk: {b_name}",
                    detail=detail,
                    location=(b_lat, building["longitude"]),
                    score=count,
                ))

        recs.sort(key=lambda r: r.score, reverse=True)
        return recs

    def investment_priority_ranking(self) -> pd.DataFrame:
        """Rank sites by composite investment score."""
        if self.charging_sites.empty:
            return pd.DataFrame()

        rows = []
        for _, site in self.charging_sites.iterrows():
            lat, lon = site["latitude"], site["longitude"]
            name = site["charge_point_location"]
            cat = site["site_category"]

            # Risk level at this location
            if not self.predictions.empty:
                dists = haversine_vec(
                    lat, lon,
                    self.predictions["lat"].values,
                    self.predictions["lon"].values,
                )
                nearest_idx = dists.argmin()
                risk = self.predictions.iloc[nearest_idx]
                risk_level = risk["risk_level"]
                risk_score = {"High": 1.0, "Medium": 0.5, "Low": 0.1}.get(risk_level, 0.1)
            else:
                risk_level = "Unknown"
                risk_score = 0.1

            # Nearby outage count
            if not self.outages.empty and "latitude" in self.outages.columns:
                dists = haversine_vec(lat, lon, self.outages["latitude"].values, self.outages["longitude"].values)
                nearby_count = (dists <= 3.218).sum()  # 2 miles
                nearby_hours = pd.to_numeric(self.outages.loc[dists <= 3.218, "duration-hours"], errors="coerce").sum()
            else:
                nearby_count, nearby_hours = 0, 0

            # V2X bonus
            v2x_bonus = 0.1 if cat == "V2X Chargepoint" else 0.0

            # Composite score
            composite = (
                risk_score * 0.4
                + min(nearby_count / 50, 1.0) * 0.3
                + min(nearby_hours / 1000, 1.0) * 0.2
                + v2x_bonus * 0.1
            )

            rows.append({
                "site_name": name,
                "category": cat,
                "lat": lat,
                "lon": lon,
                "risk_level": risk_level,
                "nearby_outages": nearby_count,
                "nearby_hours": round(nearby_hours, 1),
                "composite_score": round(composite, 3),
            })

        df = pd.DataFrame(rows).sort_values("composite_score", ascending=False).reset_index(drop=True)
        return df

    # ------------------------------------------------------------------
    # Natural language interface
    # ------------------------------------------------------------------

    def ask(self, question: str) -> str:
        """Answer a natural language question about risk and recommendations.

        Uses template-based NLG by default.  If an LLM API key is set,
        the structured context is sent to the LLM for richer answers.
        """
        q = question.lower().strip()

        # Try LLM first
        llm_answer = self._try_llm(question)
        if llm_answer:
            return llm_answer

        # Template-based fallback
        if any(w in q for w in ["highest risk", "most risk", "worst area", "riskiest"]):
            return self._answer_highest_risk()
        if any(w in q for w in ["charger", "charging station", "where to put", "deploy", "v2x"]):
            return self._answer_charger_placement()
        if any(w in q for w in ["winter", "cold", "storm"]):
            return self._answer_winter_risk()
        if any(w in q for w in ["community", "village hall", "building"]):
            return self._answer_community()
        if any(w in q for w in ["investment", "priority", "rank", "budget"]):
            return self._answer_investment()
        if any(w in q for w in ["summary", "overview", "report"]):
            return self._answer_summary()

        return (
            "I can help with questions about outage risk, charging station placement, "
            "community impact, and investment priorities. Try asking:\n"
            "• \"What areas are highest risk?\"\n"
            "• \"Where should we put new chargers?\"\n"
            "• \"What's the winter risk?\"\n"
            "• \"Show investment priorities\""
        )

    def _answer_highest_risk(self) -> str:
        high = self.predictions[self.predictions["risk_level"] == "High"].nlargest(5, "confidence")
        if high.empty:
            return "No high-risk areas identified in the current predictions."
        lines = ["**Top 5 highest-risk grid cells:**\n"]
        for i, (_, cell) in enumerate(high.iterrows(), 1):
            lines.append(
                f"{i}. ({cell['lat']:.4f}, {cell['lon']:.4f}) — "
                f"Confidence: {cell['confidence']:.0%}, "
                f"P(High): {cell.get('prob_high', 0):.0%}"
            )
        return "\n".join(lines)

    def _answer_charger_placement(self) -> str:
        recs = self.charging_station_recommendations()
        if not recs:
            return "No urgent V2X deployment gaps identified."
        lines = ["**Recommended V2X deployment locations:**\n"]
        for i, rec in enumerate(recs[:5], 1):
            lines.append(f"{i}. {rec.title}\n   {rec.detail}")
        return "\n".join(lines)

    def _answer_winter_risk(self) -> str:
        if self.outages.empty or "season" not in self.outages.columns:
            return "No seasonal data available."
        winter = self.outages[self.outages["season"] == "Winter"]
        total = len(self.outages)
        pct = len(winter) / total * 100 if total > 0 else 0
        avg_dur = pd.to_numeric(winter["duration-hours"], errors="coerce").mean()
        return (
            f"**Winter Risk Assessment:**\n\n"
            f"• {len(winter)} winter outages ({pct:.0f}% of all outages)\n"
            f"• Average winter outage duration: {avg_dur:.1f} hours\n"
            f"• Winter outages tend to be longer and affect more customers due to "
            f"severe weather conditions.\n\n"
            f"Recommendation: Prioritise V2X deployment in areas with >40% winter outage ratio."
        )

    def _answer_community(self) -> str:
        if self.community_buildings.empty:
            return "No community buildings identified in the dataset."
        lines = [f"**Community Building Risk Assessment:** ({len(self.community_buildings)} buildings found)\n"]
        for _, b in self.community_buildings.iterrows():
            name = b["charge_point_location"]
            cat = b.get("site_category", "Unknown")
            lines.append(f"• {name} — {cat}")
        return "\n".join(lines)

    def _answer_investment(self) -> str:
        ranking = self.investment_priority_ranking()
        if ranking.empty:
            return "No investment data available."
        lines = ["**Top 5 Investment Priorities:**\n"]
        for i, (_, row) in enumerate(ranking.head(5).iterrows(), 1):
            lines.append(
                f"{i}. {row['site_name']} (Score: {row['composite_score']:.3f})\n"
                f"   Risk: {row['risk_level']}, "
                f"Nearby outages: {row['nearby_outages']}, "
                f"Hours lost: {row['nearby_hours']}"
            )
        return "\n".join(lines)

    def _answer_summary(self) -> str:
        total_cells = len(self.predictions)
        high = len(self.predictions[self.predictions["risk_level"] == "High"])
        medium = len(self.predictions[self.predictions["risk_level"] == "Medium"])
        low = len(self.predictions[self.predictions["risk_level"] == "Low"])
        total_outages = len(self.outages)

        return (
            f"**Risk Model Summary:**\n\n"
            f"• Grid cells analysed: {total_cells}\n"
            f"• High risk: {high} cells ({high/total_cells*100:.0f}%)\n"
            f"• Medium risk: {medium} cells ({medium/total_cells*100:.0f}%)\n"
            f"• Low risk: {low} cells ({low/total_cells*100:.0f}%)\n"
            f"• Historic outages used: {total_outages:,}\n"
            f"• Community buildings tracked: {len(self.community_buildings)}"
        )

    # ------------------------------------------------------------------
    # LLM integration (optional)
    # ------------------------------------------------------------------

    def _try_llm(self, question: str) -> str | None:
        """Attempt to answer via an LLM API if credentials are available."""
        xiaomi_key = os.environ.get("XIAOMI_API_KEY", "").strip()
        openai_key = os.environ.get("OPENAI_API_KEY", "").strip()
        anthropic_key = os.environ.get("ANTHROPIC_API_KEY", "").strip()

        # Priority: XIAOMI_API_KEY > OPENAI_API_KEY > ANTHROPIC_API_KEY
        if xiaomi_key:
            return self._call_xiaomi(xiaomi_key, self._build_llm_context(), question)
        if openai_key:
            return self._call_openai(openai_key, self._build_llm_context(), question)
        if anthropic_key:
            return self._call_anthropic(anthropic_key, self._build_llm_context(), question)
        return None

    def _build_llm_context(self) -> str:
        """Build structured context string for the LLM."""
        parts = []

        # Risk summary
        total = len(self.predictions)
        if total > 0:
            high = len(self.predictions[self.predictions["risk_level"] == "High"])
            parts.append(f"RISK MODEL: {total} grid cells analysed. {high} classified as High risk.")

        # Top outages
        if not self.outages.empty:
            parts.append(f"HISTORIC OUTAGES: {len(self.outages)} records.")
            if "district_name" in self.outages.columns:
                top_district = self.outages["district_name"].value_counts().head(3)
                parts.append(f"Top districts: {top_district.to_dict()}")

        # Community buildings
        if not self.community_buildings.empty:
            names = self.community_buildings["charge_point_location"].tolist()
            parts.append(f"COMMUNITY BUILDINGS: {len(names)} — {', '.join(names[:5])}")

        # Charging sites
        if not self.charging_sites.empty:
            v2x = len(self.charging_sites[self.charging_sites["site_category"] == "V2X Chargepoint"])
            parts.append(f"CHARGING SITES: {len(self.charging_sites)} total, {v2x} V2X.")

        return "\n".join(parts)

    def _call_openai(self, api_key: str, context: str, question: str) -> str | None:
        try:
            import requests
            resp = requests.post(
                "https://api.openai.com/v1/chat/completions",
                headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
                json={
                    "model": "gpt-4o-mini",
                    "messages": [
                        {"role": "system", "content": (
                            "You are a grid resilience analyst for Electricity North West. "
                            "Answer questions about outage risk, EV charging deployment, "
                            "and community impact using the provided data context. "
                            "Be concise and actionable."
                        )},
                        {"role": "user", "content": f"DATA CONTEXT:\n{context}\n\nQUESTION: {question}"},
                    ],
                    "max_tokens": 500,
                    "temperature": 0.3,
                },
                timeout=30,
            )
            resp.raise_for_status()
            return resp.json()["choices"][0]["message"]["content"]
        except Exception as exc:
            log.warning("OpenAI call failed: %s", exc)
            return None

    def _call_anthropic(self, api_key: str, context: str, question: str) -> str | None:
        try:
            import requests
            resp = requests.post(
                "https://api.anthropic.com/v1/messages",
                headers={
                    "x-api-key": api_key,
                    "anthropic-version": "2023-06-01",
                    "content-type": "application/json",
                },
                json={
                    "model": "claude-3-5-haiku-20241022",
                    "max_tokens": 500,
                    "messages": [
                        {"role": "user", "content": (
                            f"You are a grid resilience analyst for Electricity North West.\n\n"
                            f"DATA CONTEXT:\n{context}\n\nQUESTION: {question}"
                        )},
                    ],
                },
                timeout=30,
            )
            resp.raise_for_status()
            return resp.json()["content"][0]["text"]
        except Exception as exc:
            log.warning("Anthropic call failed: %s", exc)
            return None

    def _call_xiaomi(self, api_key: str, context: str, question: str) -> str | None:
        """Call Xiaomi LLM API."""
        try:
            import requests
            resp = requests.post(
                "https://api.xiaomi.com/v1/chat/completions",
                headers={
                    "Authorization": f"Bearer {api_key}",
                    "Content-Type": "application/json"
                },
                json={
                    "model": "xiaomi-chat",
                    "messages": [
                        {"role": "system", "content": (
                            "You are a grid resilience analyst for Electricity North West. "
                            "Answer questions about outage risk, EV charging deployment, "
                            "and community impact using the provided data context. "
                            "Be concise and actionable."
                        )},
                        {"role": "user", "content": f"DATA CONTEXT:\n{context}\n\nQUESTION: {question}"},
                    ],
                    "max_tokens": 500,
                    "temperature": 0.3,
                },
                timeout=30,
            )
            resp.raise_for_status()
            return resp.json()["choices"][0]["message"]["content"]
        except Exception as exc:
            log.warning("Xiaomi API call failed: %s", exc)
            return None

    # ------------------------------------------------------------------
    # Full report
    # ------------------------------------------------------------------

    def generate_all_insights(self) -> InsightReport:
        """Generate the full recommendation report."""
        report = InsightReport()

        report.recommendations.extend(self.charging_station_recommendations())
        report.recommendations.extend(self.grid_resilience_recommendations())
        report.recommendations.extend(self.community_impact_recommendations())

        # Sort by priority
        priority_order = {"Critical": 0, "High": 1, "Medium": 2, "Low": 3}
        report.recommendations.sort(key=lambda r: priority_order.get(r.priority, 9))

        report.investment_ranking = self.investment_priority_ranking()

        # Summary
        report.summary = self._answer_summary()

        return report


_report_mem_cache = None
_report_mem_mtime: float = 0.0


def generate_report_cached(predictions, outages, charging_sites, force: bool = False):
    """Generate recommendations with persistent + in-memory pickle cache."""
    global _report_mem_cache, _report_mem_mtime
    import joblib

    if not force and REPORT_CACHE.exists():
        mtime = REPORT_CACHE.stat().st_mtime
        if _report_mem_cache is not None and mtime == _report_mem_mtime:
            return _report_mem_cache
        log.info("Loading recommendations from cache: %s", REPORT_CACHE)
        _report_mem_cache = joblib.load(REPORT_CACHE)
        _report_mem_mtime = mtime
        return _report_mem_cache

    engine = RecommendationEngine(predictions, outages, charging_sites)
    report = engine.generate_all_insights()
    REPORT_CACHE.parent.mkdir(parents=True, exist_ok=True)
    joblib.dump(report, REPORT_CACHE)
    _report_mem_cache = report
    _report_mem_mtime = REPORT_CACHE.stat().st_mtime
    log.info("Recommendations cached to %s", REPORT_CACHE)
    return report


def invalidate_report_cache():
    """Delete the recommendations cache (called after new data fetch)."""
    global _report_mem_cache, _report_mem_mtime
    if REPORT_CACHE.exists():
        REPORT_CACHE.unlink()
        log.info("Recommendations cache invalidated: %s", REPORT_CACHE)
    _report_mem_cache = None
    _report_mem_mtime = 0.0


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main():
    import argparse

    parser = argparse.ArgumentParser(description="Business recommendation engine.")
    parser.add_argument("--ask", type=str, help="Ask a natural language question.")
    args = parser.parse_args()

    # Load data
    from advanced_charts.risk_model import load_models, predict_cells, build_grid_features, assign_risk_labels, FEATURE_COLS

    outages = pd.read_csv(DATA_DIR / "df_cleaned.csv", parse_dates=["incident_date_time"])
    features = build_grid_features(outages)
    features = assign_risk_labels(features)

    rf_model, xgb_model, xgb_le = load_models()
    predictions = predict_cells(rf_model, features)

    charging_sites = pd.read_csv(CHARGING_SITES_FILE) if CHARGING_SITES_FILE.exists() else None

    engine = RecommendationEngine(predictions, outages, charging_sites)

    if args.ask:
        print(engine.ask(args.ask))
    else:
        report = engine.generate_all_insights()
        print(report.summary)
        print("\n" + "=" * 60)
        for rec in report.recommendations[:10]:
            print(f"\n[{rec.priority}] {rec.category}: {rec.title}")
            print(f"  {rec.detail}")


if __name__ == "__main__":
    main()
